FROM node:22-bullseye

RUN apt update && apt install -y \
    zsh \
    vim \
    locales 

RUN sed -i '/en_US.UTF-8/s/^# //g' /etc/locale.gen && \
    locale-gen


ENV LANG en_US.UTF-8  
ENV LANGUAGE en_US:en  
ENV LC_ALL en_US.UTF-8  

RUN sh -c "$(wget https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh -O -)" && \
    echo "PROMPT='%(?:%{\$fg_bold[green]%}%1{➜%} :%{\$fg_bold[red]%}%1{➜%} ) %{\$fg[cyan]%}%d%{\$reset_color%} \
\$(git_prompt_info)'" >> /root/.oh-my-zsh/themes/robbyrussell.zsh-theme && \
    git config --global --add safe.directory /workspaces/FantasyForum