version: '3.8'

volumes:
  postgres-data:

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile_frontend
    env_file: 
      - .env

    volumes:
      - ..:/workspaces/FantasyForum:cached
      
    command: sleep infinity

    network_mode: service:db


  backend:
    build: 
      context: .
      dockerfile: Dockerfile_backend
    env_file:
        # Ensure that the variables in .env match the same variables in devcontainer.json
        - .env

    volumes:
      - ..:/workspaces/FantasyForum:cached
      - /home/sqa/Desktop/Docker/go-pkg/:/go/pkg/mod
      
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    network_mode: service:db

    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally. 
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  db:
    image: postgres:15.6
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      # Ensure that the variables in .env match the same variables in devcontainer.json
      - .env


    # Add "forwardPorts": ["5432"] to **devcontainer.json** to forward PostgreSQL locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)
